name: Version Auto-PR
on:
  push:
    branches:
      - "Update-v*"

jobs:
  pull-request:
    name: Open PR to main
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: pull-request
        uses: repo-sync/pull-request@v2
        with:
          source_branch: ""
          pr_reviewer: "dakota002"
          destination_branch: "main"
