name: Update From Package
on:
  pull_request:
    types:
      - "closed"
    paths:
      - "package.json"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      # Checkout
      - name: Checkout
        uses: actions/checkout@v2
      # Check for version change
      - name: Get versions
        id: get_versions
        run: |
          PREVIOUS_VERSION=$(git show HEAD^:package.json | jq -r '.version')
          echo "::set-output name=PREVIOUS_VERSION::$PREVIOUS_VERSION"
          NEW_VERSION=$(git show HEAD:package.json | jq -r '.version')
          echo "::set-output name=NEW_VERSION::$NEW_VERSION"

      - name: Update Links from version
        if: ${{steps.get_versions.outputs.PREVIOUS_VERSION != steps.get_versions.outputs.NEW_VERSION}}
        run: |
          node updateTag.mjs
